export enum RouterNames {
  CLIENT_HOME = "CL_HOME",
  CLIENT_SERVICIOS = "CL_SERVICIOS",
  CLIENT_CONTRATISTA_BASE = "CL_CONTRATISTA_BASE",
  CLIENT_CONTRATISTA = "CL_CONTRATISTA",
  CLIENT_CONTRATISTA_CHAT = "CL_CONTRATISTA_CHAT",
}
